### ISSUE TITLE
Delete a Restaurant

### ISSUE THREAD

**Issue by enricoferrari** [Symphono/wfl#45]

**Comment by TNagaraja** [comment]
How should deleting a restaurant affect a food order that is associated with it? Should it also be deleted?

**Comment by JChapman202** [comment]
@TNagaraja I think we led you astray on this issue.  The details of the story should have been filled in.  Worse, someone should have answered your question.  I see that the current PR did not handle this situation, but I think you're asking the exact right question here.  Personally I think we should create a new issue and describe any needed restrictions related to deleting of restaurants.

@enricoferrari you have thoughts on this?  Want to create the new issue?

**Comment by enricoferrari** [comment]
Tej and I talked about this yesterday.  I myself do not know why we have a story to delete a restaurant. I don't see it as something this API needs right now.

**Comment by JChapman202** [comment]
I believe you created this issue during our IPM last week.  At the time it was discussed as a "in case I fat fingered something" when creating it.

**Comment by enricoferrari** [comment]
Not that it matters but I wanted to cut excess stuff like this out from what I consider minimal.  In any case, I am fine either saying: This can leave orders with references to non-existant Id's  OR (my preference) have this action search all food orders for any use of this restaurant and refuse to delete it if orders exist.  I prefer the second one because it solves the issue temporarily.  I don't think we have thought this story through.. maybe there is a more soft delete feature like ORders has and those restaurants become unusable for new orders etc... At this stage I would prefer we do not spend time on this.

**Comment by JChapman202** [comment]
I completely agree with your recommendation.  We should ensure no food orders exist for that restaurant before removing it.  We should write a new story to capture that.
